# Generated by Django 5.2 on 2025-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biologicalcategory",
            options={
                "verbose_name": "Kategorie biologického systému",
                "verbose_name_plural": "Kategorie biologického systému",
            },
        ),
        migrations.AlterField(
            model_name="biologicalcategory",
            name="name",
            field=models.CharField(
                help_text="Vlož kategorii biologického systému",
                max_length=255,
                unique=True,
                verbose_name="Kategorie",
            ),
        ),
    ]
