# Generated by Django 5.2 on 2025-04-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_alter_biologicalcategory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biologicalcategory",
            old_name="name",
            new_name="category",
        ),
    ]
