# Generated by Django 5.2 on 2025-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_rename_name_biologicalcategory_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biologicalcategory",
            options={
                "verbose_name": "Biological system category",
                "verbose_name_plural": "Biological system categories",
            },
        ),
        migrations.RemoveField(
            model_name="biologicalcategory",
            name="category",
        ),
        migrations.AddField(
            model_name="biologicalcategory",
            name="category_name",
            field=models.CharField(
                default=1,
                help_text="Enter the name of the biological system category",
                max_length=255,
                unique=True,
                verbose_name="Category name",
            ),
            preserve_default=False,
        ),
    ]
