# Generated by Django 5.2 on 2025-04-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="name",
            new_name="author_name",
        ),
    ]
