# Generated by Django 5.2 on 2025-07-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/"),
        ),
    ]
